name: Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v3

    - name: Download Oracle Instant Client
      run: |
        wget https://download.oracle.com/otn_software/linux/instantclient/2390000/instantclient-basic-linux.x64-23.9.0.25.07.zip -O instantclient.zip
        unzip instantclient.zip -d $HOME/oracle_instantclient
        echo "$HOME/oracle_instantclient/instantclient_21_13" >> $GITHUB_PATH

    - name: Set ORACLE_CLIENT_PATH in settings.py
      run: |
        echo "ORACLE_CLIENT_PATH = '$HOME/oracle_instantclient/instantclient_21_13'" > settings.py

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Execute Robot Framework Tests
      run: |
        mkdir -p results
        robot --outputdir results Tests/test.robot

    - name: Upload Robot Framework Results
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: results/
