name: Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Execute Robot Framework Tests
      run: |
        mkdir -p results
        robot --outputdir results tests/test_connectivity.robot

    - name: Upload Robot Framework Results
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: results/
